### ISSUE TITLE
找不到ppt按钮

### ISSUE THREAD

**Issue by hujihan** [xuhe2/VideoBot#2]
now time is: 2024-05-30 12:11:43
capture name: [ 中国商业视觉发展 ]
找不到ppt按钮
找不到ppt按钮

**Comment by xuhe2** [comment]
这个项目好久没修了,建议使用 [zjooc_fucker](https://github.com/Error063/zjooc_fucker) ,这个是基于API逆向的刷zjooc的代码, 我写了docker部署方式, 内存占用50MB不到, 性能更好, 一分钟直接完成全部课程视频

**Comment by xuhe2** [comment]
> 这个项目好久没修了,建议使用 [zjooc_fucker](https://github.com/Error063/zjooc_fucker) ,这个是基于API逆向的刷zjooc的代码, 我写了docker部署方式, 内存占用50MB不到, 性能更好, 一分钟直接完成全部课程视频

刚刚看到你在那个项目下的ISSUE了, 我已经在那个issue下面回复了你
